return {
  {
    'CRAG666/code_runner.nvim',
    cmd = { 'RunCode', 'RunFile', 'RunProject' },
    keys = {
      { '<leader>rr', '<cmd>RunCode<CR>', desc = 'Run Code' },
      { '<leader>rf', '<cmd>RunFile<CR>', desc = 'Run File' },
      { '<leader>rp', '<cmd>RunProject<CR>', desc = 'Run Project' },
    },
    config = function()
      require('code_runner').setup {
        mode = 'term', -- term, tab, float, toggleterm
        focus = true,
        startinsert = true,
        term = {
          position = 'bot',
          size = 8,
        },
        filetype = {
          javascript = 'node',
          java = 'cd $dir && javac $fileName && java $fileNameWithoutExt',
          c = 'cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          zig = 'zig run',
          cpp = 'cd $dir && g++ -fexec-charset=UTF-8 -std=c++17 $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          ['objective-c'] = 'cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          php = 'php',
          python = "if [ -f .venv/bin/python ]; then .venv/bin/python -u '$fileName'; elif [ -f venv/bin/python ]; then venv/bin/python -u '$fileName'; else python -u '$fileName'; fi",
          perl = 'perl',
          perl6 = 'perl6',
          ruby = 'ruby',
          go = 'go mod tidy && go run .',
          lua = 'lua',
          groovy = 'groovy',
          powershell = 'pwsh -ExecutionPolicy ByPass -File',
          bat = 'cmd /c',
          shellscript = 'bash',
          fsharp = 'fsi',
          csharp = 'scriptcs',
          vbscript = 'cscript //Nologo',
          typescript = 'ts-node',
          coffeescript = 'coffee',
          scala = 'scala',
          swift = 'swift',
          julia = 'julia',
          crystal = 'crystal',
          ocaml = 'ocaml',
          r = 'Rscript',
          applescript = 'osascript',
          clojure = 'lein exec',
          haxe = 'haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt',
          rust = 'cd $dir && cargo run',
          racket = 'racket',
          scheme = 'csi -script',
          ahk = 'autohotkey',
          autoit = 'autoit3',
          dart = 'dart',
          pascal = 'cd $dir && fpc $fileName && $dir/$fileNameWithoutExt',
          d = 'cd $dir && dmd $fileName && $dir/$fileNameWithoutExt',
          haskell = 'runghc',
          nim = 'nim compile --verbosity:0 --hints:off --run',
          lisp = 'sbcl --script',
          kit = 'kitc --run',
          v = 'v run',
          sass = 'sass --style expanded',
          scss = 'scss --style expanded',
          less = 'cd $dir && lessc $fileName $fileNameWithoutExt.css',
          FortranFreeForm = 'cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          ['fortran-modern'] = 'cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          ['fortran_fixed-form'] = 'cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          fortran = 'cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt',
          sml = 'cd $dir && sml $fileName',
          mojo = 'mojo run',
        },
      }
    end,
  },
}
